import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import CustomerForm from './CustomerForm';
import { addCustomer } from '../services/apiService';

vi.mock('../services/apiService', () => ({
  addCustomer: vi.fn()
}));

describe('CustomerForm', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('submits manual customer data successfully and resets the form', async () => {
    const onCustomerAdded = vi.fn();
    addCustomer.mockResolvedValue({ personId: 'C-100', name: 'Alice' });

    render(<CustomerForm onCustomerAdded={onCustomerAdded} />);

    const nameInput = screen.getByLabelText('Name');
    const ageInput = screen.getByLabelText('Age');
    const moneyInput = screen.getByLabelText('Money');

    fireEvent.change(nameInput, { target: { value: 'Alice' } });
    fireEvent.change(ageInput, { target: { value: '29' } });
    fireEvent.change(moneyInput, { target: { value: '150.75' } });

    fireEvent.click(screen.getByRole('button', { name: 'Add Customer' }));

    await waitFor(() => {
      expect(addCustomer).toHaveBeenCalledWith({
        name: 'Alice',
        age: 29,
        money: 150.75,
        autoGenerate: false
      });
    });

    expect(
      await screen.findByText('Customer added successfully! ID: C-100, Name: Alice')
    ).toBeInTheDocument();
    expect(onCustomerAdded).toHaveBeenCalledWith({ personId: 'C-100', name: 'Alice' });

    expect(nameInput).toHaveValue('');
    expect(ageInput).toHaveValue(null);
    expect(moneyInput).toHaveValue(null);
  });

  it('uses auto-generated branch when checkbox is enabled', async () => {
    addCustomer.mockResolvedValue({ personId: 'AUTO-1', name: 'AutoGenerated' });

    render(<CustomerForm />);

    fireEvent.click(screen.getByRole('checkbox', { name: 'Auto-generate customer data' }));

    expect(screen.queryByRole('textbox')).not.toBeInTheDocument();
    expect(screen.queryByRole('spinbutton')).not.toBeInTheDocument();

    fireEvent.click(screen.getByRole('button', { name: 'Add Customer' }));

    await waitFor(() => {
      expect(addCustomer).toHaveBeenCalledWith({
        name: 'AutoGenerated',
        age: 0,
        money: 0,
        autoGenerate: true
      });
    });

    expect(
      await screen.findByText('Customer added successfully! ID: AUTO-1, Name: AutoGenerated')
    ).toBeInTheDocument();
  });

  it('shows failure message when addCustomer rejects', async () => {
    addCustomer.mockRejectedValue(new Error('Validation failed'));

    render(<CustomerForm />);

    const nameInput = screen.getByLabelText('Name');
    const ageInput = screen.getByLabelText('Age');
    const moneyInput = screen.getByLabelText('Money');

    fireEvent.change(nameInput, { target: { value: 'Bad Input' } });
    fireEvent.change(ageInput, { target: { value: '10' } });
    fireEvent.change(moneyInput, { target: { value: '1.00' } });

    fireEvent.click(screen.getByRole('button', { name: 'Add Customer' }));

    expect(await screen.findByText('Failed to add customer: Validation failed')).toBeInTheDocument();
  });
});
