import React, { useState } from 'react';
import PropTypes from 'prop-types';
import { addCustomer } from '../services/apiService';

const CustomerForm = ({ onCustomerAdded = null }) => {
    const [name, setName] = useState('');
    const [age, setAge] = useState('');
    const [money, setMoney] = useState('');
    const [autoGenerate, setAutoGenerate] = useState(false);
    const [statusMessage, setStatusMessage] = useState('');

    const handleSubmit = async (event) => {
        event.preventDefault();
        setStatusMessage('Adding customer...');
        try {
            const customerData = autoGenerate
                ? { name: 'AutoGenerated', age: 0, money: 0, autoGenerate: true }
                : { name, age: Number.parseInt(age, 10), money: Number.parseFloat(money), autoGenerate: false };

            const newCustomer = await addCustomer(customerData);
            setStatusMessage(`Customer added successfully! ID: ${newCustomer.personId}, Name: ${newCustomer.name}`);
            setName('');
            setAge('');
            setMoney('');
            if (onCustomerAdded) {
                onCustomerAdded(newCustomer);
            }
        } catch (error) {
            setStatusMessage(`Failed to add customer: ${error.message}`);
        }
    };

    return (
        <div>
            <h3>Add New Customer</h3>
            <form onSubmit={handleSubmit}>
                <div>
                    <label htmlFor="autoGenerateCustomer">
                        <input
                            id="autoGenerateCustomer"
                            type="checkbox"
                            checked={autoGenerate}
                            onChange={(event) => setAutoGenerate(event.target.checked)}
                        />
                        Auto-generate customer data
                    </label>
                </div>
                {!autoGenerate && (
                    <>
                        <div>
                            <label htmlFor="customerName">Name</label>
                            <input id="customerName" type="text" value={name} onChange={(event) => setName(event.target.value)} required />
                        </div>
                        <div>
                            <label htmlFor="customerAge">Age</label>
                            <input id="customerAge" type="number" value={age} onChange={(event) => setAge(event.target.value)} required />
                        </div>
                        <div>
                            <label htmlFor="customerMoney">Money</label>
                            <input id="customerMoney" type="number" step="0.01" value={money} onChange={(event) => setMoney(event.target.value)} required />
                        </div>
                    </>
                )}
                <button type="submit" style={{ marginTop: '10px' }}>Add Customer</button>
            </form>
            {statusMessage && <p aria-live="polite">{statusMessage}</p>}
        </div>
    );
};

CustomerForm.propTypes = {
    onCustomerAdded: PropTypes.func,
};

export default CustomerForm;
