import React, { useState } from 'react';
import { addCustomer } from '../services/apiService';

const CustomerForm = ({ onCustomerAdded }) => {
    const [name, setName] = useState('');
    const [age, setAge] = useState('');
    const [money, setMoney] = useState('');
    const [autoGenerate, setAutoGenerate] = useState(false);
    const [statusMessage, setStatusMessage] = useState('');

    const handleSubmit = async (e) => {
        e.preventDefault();
        setStatusMessage('Adding customer...');
        try {
            const customerData = autoGenerate 
                ? { name: 'AutoGenerated', age: 0, money: 0, autoGenerate: true } // Backend will generate details
                : { name, age: parseInt(age), money: parseFloat(money), autoGenerate: false };
            
            const newCustomer = await addCustomer(customerData);
            setStatusMessage(`Customer added successfully! ID: ${newCustomer.personId}, Name: ${newCustomer.name}`);
            setName('');
            setAge('');
            setMoney('');
            if (onCustomerAdded) {
                onCustomerAdded(newCustomer);
            }
        } catch (error) {
            setStatusMessage(`Failed to add customer: ${error.message}`);
        }
    };

    return (
        <div>
            <h3>Add New Customer</h3>
            <form onSubmit={handleSubmit}>
                <div>
                    <label>
                        <input 
                            type="checkbox" 
                            checked={autoGenerate} 
                            onChange={(e) => setAutoGenerate(e.target.checked)} 
                        />
                        Auto-generate customer data
                    </label>
                </div>
                {!autoGenerate && (
                    <>
                        <div>
                            <label>Name: </label>
                            <input type="text" value={name} onChange={(e) => setName(e.target.value)} required />
                        </div>
                        <div>
                            <label>Age: </label>
                            <input type="number" value={age} onChange={(e) => setAge(e.target.value)} required />
                        </div>
                        <div>
                            <label>Money: </label>
                            <input type="number" step="0.01" value={money} onChange={(e) => setMoney(e.target.value)} required />
                        </div>
                    </>
                )}
                <button type="submit" style={{marginTop: '10px'}}>Add Customer</button>
            </form>
            {statusMessage && <p>{statusMessage}</p>}
        </div>
    );
};

export default CustomerForm;
