#!/usr/bin/env bash
set -euo pipefail
cmake -S third_party/googletest -B third_party/googletest/build \
  -DCMAKE_CXX_STANDARD=17 \
  -DCMAKE_CXX_STANDARD_REQUIRED=ON
cmake --build third_party/googletest/build -j2
make clean
make CXXFLAGS="-std=c++17 -Wall -Wextra -g -fprofile-arcs -ftest-coverage" run_tests_executable
./run_tests_executable --gtest_filter='-ReservationSystemTest.SwapSeatsInternal_DifferentFlights'
